[package]
name = "autogram"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.8"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }

time = "0.3.36"

tdlib-tl-gen = "0.5.0"
tdlib-tl-parser = "0.2.0"
tdlib = "0.10.0"
