[package]
name = "autogram"
version = "0.10.1"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.8"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }

time = "0.3.36"

tdlib-rs-gen = "1.0.3"
tdlib-rs-parser = "1.0.3"
tdlib-rs = { version = "1.0.3", features = [ "download-tdlib" ] }

clap = { version = "4.5.4", features = ["derive"] }

anyhow = "1.0"

reqwest = { version = "0.12.5", features = ["json"] }
