[package]
name = "autogram"
version = "0.12.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
serde_with = "3.12.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "time", "local-time"] }

time = "0.3.37"

tdlib-rs-gen = "1.0.5"
tdlib-rs-parser = "1.0.5"
tdlib-rs = { version = "1.0.5", features = [ "download-tdlib" ] }

clap = { version = "4.5.23", features = ["derive"] }

anyhow = "1.0.95"

reqwest = { version = "0.12.12", features = ["json"] }
