[package]
name = "autogram"
version = "0.12.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }

serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
serde_with = "3.9.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }

time = "0.3.36"

tdlib-rs-gen = "1.0.5"
tdlib-rs-parser = "1.0.5"
tdlib-rs = { version = "1.0.5", features = [ "download-tdlib" ] }

clap = { version = "4.5.16", features = ["derive"] }

anyhow = "1.0"

reqwest = { version = "0.12.7", features = ["json"] }
